spring.application.name=labortrack-backend

server.port=8080

# POSTGRESQL
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

# JWT
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=${JWT_EXPIRATION:1h}

# JPA & HIBERNATE
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:false}

# FLYWAY
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# CORS
security.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

# IN-MEMORY RATE LIMITING
security.rate-limit.enabled=${RATE_LIMIT_ENABLED:true}

security.rate-limit.global.requests=${RATE_LIMIT_GLOBAL_REQUESTS:120}
security.rate-limit.global.duration=${RATE_LIMIT_GLOBAL_DURATION:1m}

security.rate-limit.login.requests=${RATE_LIMIT_LOGIN_REQUESTS:10}
security.rate-limit.login.duration=${RATE_LIMIT_LOGIN_DURATION:1m}

security.rate-limit.register.requests=${RATE_LIMIT_REGISTER_REQUESTS:5}
security.rate-limit.register.duration=${RATE_LIMIT_REGISTER_DURATION:1h}

security.rate-limit.change-password.requests=${RATE_LIMIT_CHANGE_PASSWORD_REQUESTS:10}
security.rate-limit.change-password.duration=${RATE_LIMIT_CHANGE_PASSWORD_DURATION:15m}