-- for sensitive email chars. This ensure uniqueness like test@email.com and Test@email.com are treated as the same.
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE companies (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(150) NOT NULL,
	email citext NOT NULL UNIQUE,
	phone VARCHAR(30),
	timezone VARCHAR(64) NOT NULL,
	active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	company_id BIGINT NOT NULL,
	email citext NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	role VARCHAR(30) NOT NULL,
	enabled BOOLEAN NOT NULL DEFAULT TRUE,
	must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	
	CONSTRAINT fk_users_company
        	FOREIGN KEY (company_id) REFERENCES companies(id),

	-- role can only be admin, employee
	CONSTRAINT chk_users_role
        	CHECK (role IN ('ADMIN', 'EMPLOYEE')),
	
	CONSTRAINT uq_users_id_company UNIQUE (id, company_id)
);

CREATE TABLE employees (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	company_id BIGINT NOT NULL,
	user_id BIGINT NOT NULL UNIQUE,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	phone VARCHAR(30),
	hourly_rate NUMERIC(10,2) NOT NULL,
	profile_image_url VARCHAR(500),
	status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
	hire_date DATE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

	CONSTRAINT fk_employees_company
        	FOREIGN KEY (company_id) REFERENCES companies(id),

    	CONSTRAINT fk_employees_user_company
    		FOREIGN KEY (user_id, company_id) REFERENCES users(id, company_id),
	
	-- status can only be active, inactive, terminated
    	CONSTRAINT chk_employees_status
        	CHECK (status IN ('ACTIVE', 'INACTIVE', 'TERMINATED')),
	
	-- positive hourly pay rate required
    	CONSTRAINT chk_employees_hourly_rate
        	CHECK (hourly_rate >= 0),
	
	CONSTRAINT uq_employees_id_company UNIQUE (id, company_id)
);
CREATE TABLE work_sessions ( 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	company_id BIGINT NOT NULL,
	employee_id BIGINT NOT NULL,
	clock_in_time TIMESTAMPTZ NOT NULL,
	clock_out_time TIMESTAMPTZ,
	status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
	note TEXT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	
	CONSTRAINT fk_work_sessions_company
        	FOREIGN KEY (company_id) REFERENCES companies(id),

    	CONSTRAINT fk_work_sessions_employee_company
    		FOREIGN KEY (employee_id, company_id) REFERENCES employees(id, company_id),
	
	-- status can only be open, closed, adjusted
   	CONSTRAINT chk_work_sessions_status
        	CHECK (status IN ('OPEN', 'CLOSED', 'ADJUSTED')),
	
	-- either clock_out is null or clock_in must be before clock_out
    	CONSTRAINT chk_work_sessions_time_order
        	CHECK (clock_out_time IS NULL OR clock_out_time > clock_in_time)
);

-- Find users that belong to a company, useful for admin management
CREATE INDEX idx_users_company_id
ON users(company_id);

-- Find employees by company and status, useful for company dashboard
CREATE INDEX idx_employees_company_status
ON employees(company_id, status);

-- Find latest clock-in history for an employee
CREATE INDEX idx_work_sessions_employee_clock_in
ON work_sessions(employee_id, clock_in_time DESC);

--  Find latest clock-in history for a company
CREATE INDEX idx_work_sessions_company_clock_in
ON work_sessions(company_id, clock_in_time DESC);

-- prevent an employee from having more than one open work session
CREATE UNIQUE INDEX ux_work_sessions_one_open_per_employee
ON work_sessions(employee_id)
WHERE status = 'OPEN';

-- Find currently clocked-in employees for a company dashboard.
CREATE INDEX idx_work_sessions_company_open
ON work_sessions(company_id, employee_id)
WHERE status = 'OPEN';
